baseURL = "https://amtoine.github.io"
languageCode = "en-us"
paginate = 5
theme = "hugo-theme-terminal"

[params]
  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "orange"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 10

  # show selector to switch language
  showLanguageSelector = true

  # set theme to full screen width
  fullWidthTheme = false

  # center theme with default width
  centerTheme = true

  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

  # set post to show the last updated
  # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
  showLastUpdated = true
  # Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
  updatedDatePrefix = "Last update"

  # set all headings to their default size (depending on browser settings)
  # it's set to `true` by default
  # oneHeadingSize = false

[languages]
  [languages.en]
    languageName = "English"
    title = "amtoine' Personal Website & Blog"
    subtitle = ""
    owner = "amtoine"
    keywords = ""
    copyright = "https://github.com/amtoine/amtoine.github.io/blob/main/LICENSE"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"

    [languages.en.params.logo]
      logoText = "Home"
      logoHomeLink = "/"

    [[languages.en.menu.main]]
      identifier = "about"
      name = "About"
      url = "/about"
      weight=1
    [[languages.en.menu.main]]
      identifier = "contact"
      name = "Contact Me"
      url = "/contact"
      weight=2
    [[languages.en.menu.main]]
      identifier = "posts"
      name = "Posts"
      url = "/posts"
      weight=3
